/* Generated by Yosys 0.9+4052 (git sha1 d061b0e, gcc 8.3.1 -fPIC -Os) */

module vsdserializer_v1(clk, load, INPUT, OUTPUT);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input [9:0] INPUT;
  output OUTPUT;
  input clk;
  input load;
  wire \tmp[0] ;
  wire \tmp[1] ;
  wire \tmp[2] ;
  wire \tmp[3] ;
  wire \tmp[4] ;
  wire \tmp[5] ;
  wire \tmp[6] ;
  wire \tmp[7] ;
  wire \tmp[8] ;
  wire \tmp[9] ;
  sky130_fd_sc_hd__mux2_2 _11_ (
    .A0(\tmp[9] ),
    .A1(OUTPUT),
    .S(load),
    .X(_09_)
  );
  sky130_fd_sc_hd__and2_2 _12_ (
    .A(load),
    .B(INPUT[0]),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(\tmp[0] ),
    .A1(INPUT[1]),
    .S(load),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(\tmp[1] ),
    .A1(INPUT[2]),
    .S(load),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(\tmp[2] ),
    .A1(INPUT[3]),
    .S(load),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(\tmp[3] ),
    .A1(INPUT[4]),
    .S(load),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(\tmp[4] ),
    .A1(INPUT[5]),
    .S(load),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(\tmp[5] ),
    .A1(INPUT[6]),
    .S(load),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(\tmp[6] ),
    .A1(INPUT[7]),
    .S(load),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(\tmp[7] ),
    .A1(INPUT[8]),
    .S(load),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(\tmp[8] ),
    .A1(INPUT[9]),
    .S(load),
    .X(_08_)
  );
  sky130_fd_sc_hd__dfxtp_2 _22_ (
    .CLK(clk),
    .D(_03_),
    .Q(\tmp[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _23_ (
    .CLK(clk),
    .D(_04_),
    .Q(\tmp[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _24_ (
    .CLK(clk),
    .D(_05_),
    .Q(\tmp[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _25_ (
    .CLK(clk),
    .D(_06_),
    .Q(\tmp[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _26_ (
    .CLK(clk),
    .D(_07_),
    .Q(\tmp[8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _27_ (
    .CLK(clk),
    .D(_08_),
    .Q(\tmp[9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _28_ (
    .CLK(clk),
    .D(_00_),
    .Q(\tmp[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _29_ (
    .CLK(clk),
    .D(_01_),
    .Q(\tmp[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _30_ (
    .CLK(clk),
    .D(_02_),
    .Q(\tmp[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _31_ (
    .CLK(clk),
    .D(_09_),
    .Q(OUTPUT)
  );
  sky130_fd_sc_hd__dfxtp_2 _32_ (
    .CLK(clk),
    .D(_10_),
    .Q(\tmp[0] )
  );
endmodule
